# fetch_esxi_facts.yml
- name: Fetch ESXi Host Facts
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  vars:
    vcenter_hostname: "192.168.121.143"
    vcenter_username: "root"
    vcenter_password: "VMware1234!"
    validate_certs: false  # set to true if using valid certs

  tasks:
    - name: Gather ESXi host facts
      community.vmware.vmware_host_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
      register: esxi_facts

    - name: Display ESXi host info
      debug:
        var: esxi_facts
