- name: Gather VMware facts
  hosts: 192.168.121.143
  gather_facts: yes
  collections:
    - community.vmware
  tasks:
    - name: Gather facts from vCenter
      vmware_vm_facts:
        hostname: 192.168.121.143
        username: root
        password: VMware1234!
        validate_certs: no
      delegate_to: localhost
